### ISSUE TITLE
注文登録(order-reception)のIF最適化とDB取得処理の追加

### ISSUE THREAD

**Issue by zami-t** [tetsuya-azami/api-grpc-integration#1]
商品情報、属性情報は改ざん防止のためidのみIFに含めるように修正する。(※ priceについてはリクエストパラメータの値との整合性チェックをするためにIFに残しても良さそう)
また、それに伴いDBから情報を取得する処理を追加する。
他プロパティ既存プロパティもIFに載せておくべきなのか再度検討。

**Comment by zami-t** [comment]
> (※ priceについてはリクエストパラメータの値との整合性チェックをするためにIFに残しても良さそう)

masterデータ更新時の不整合を防ぐのにも役立ちそう
ex.)
1. ユーザが画面で注文確定をするために商品情報を取得
2. 商品情報のmasterデータの更新(商品価格)
3. ユーザが注文確定
の場合に1と3で商品価格が異なるのでそれをバリデーションで弾ける(そもそもmasterデータの更新をユーザ影響ある時間帯でやらないというのが大事な気はするが。。。)

**Comment by tetsuya-azami** [comment]
商品情報: id, price
属性情報: id
をIFに含める形でfix。
id情報を元にmasterデータをDBから取得する処理も追加済み。

**Comment by zami-t** [comment]
商品情報: id, price
属性情報: id
をIFに含める形でfix。
id情報を元にmasterデータをDBから取得する処理も追加済み。
